## Importing Modules

In [1]:
import pandas as pd
import re

## Setting the row and Column display to max

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

## Preprocessing of Each State Data

### 1. Andhra Pradesh

In [166]:
data_AP = pd.read_excel('P2011-14.xls', sheet_name=0)

In [167]:
data_AP.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ANDHRA PRADESH Mandal selection for the Block ...,NaN,NaN,NaN,NaN
1,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name
2,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali
3,Zone -I,Srikakulam,2,Amdalavasa,Dusi
4,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru

In [168]:
data_AP = data_AP.iloc[1:].reset_index(drop=True)

data_AP.columns = data_AP.iloc[0]

data_AP = data_AP.drop(0).reset_index(drop=True)

data_AP['State Name'] = 'Andhra Pradesh'
data_AP['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [169]:
data_AP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali,Andhra Pradesh,2011-2014
1,Zone -I,Srikakulam,2,Amdalavasa,Dusi,Andhra Pradesh,2011-2014
2,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru,Andhra Pradesh,2011-2014
3,Zone -I,Vishakapatnam,4,Makavara Palem,Byyavaram,Andhra Pradesh,2011-2014
4,Zone-II,East Godavari,5,Samalkota,J.Peta,Andhra Pradesh,2011-2014

In [170]:
data_AP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali,Andhra Pradesh,2011-2014
1,Zone -I,Srikakulam,2,Amdalavasa,Dusi,Andhra Pradesh,2011-2014
2,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru,Andhra Pradesh,2011-2014
3,Zone -I,Vishakapatnam,4,Makavara Palem,Byyavaram,Andhra Pradesh,2011-2014
4,Zone-II,East Godavari,5,Samalkota,J.Peta,Andhra Pradesh,2011-2014

### 2. Assam

In [171]:
data_Assam = pd.read_excel('P2011-14.xls', sheet_name=1)

In [172]:
data_Assam.head()

  Unnamed: 0      Unnamed: 1   Unnamed: 2       Unnamed: 3     Unnamed: 4
0    Zone No   District Name  Tehsil Code     Tehsil Name   Village Name
1          I         Dhemaji            1          Dhemaji      Ghilaguri
2        NaN             NaN          NaN              NaN       Gualgaon
3        NaN             NaN          NaN              NaN         Nagaon
4        NaN       Lakhimpur            2  North Lakhimpur       Hatilung

In [173]:
data_Assam.columns = data_Assam.iloc[0]

data_Assam = data_Assam.drop(0).reset_index(drop=True)

data_Assam['State Name'] = 'Assam'
data_Assam['Year'] = '2011-2014'

In [174]:
data_Assam = data_Assam.ffill()

In [175]:
data_Assam.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,I,Dhemaji,1,Dhemaji,Ghilaguri,Assam,2011-2014
1,I,Dhemaji,1,Dhemaji,Gualgaon,Assam,2011-2014
2,I,Dhemaji,1,Dhemaji,Nagaon,Assam,2011-2014
3,I,Lakhimpur,2,North Lakhimpur,Hatilung,Assam,2011-2014
4,I,Lakhimpur,2,North Lakhimpur,Bogalijan,Assam,2011-2014

In [176]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_Assam.columns = new_column_names

### 3. Bihar

In [177]:
data_BH = pd.read_excel('P2011-14.xls', sheet_name=2)

In [178]:
data_BH.head()

,Districts and Tehsils of Bihar and Jharkhand for block period 2011-14,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Bihar,NaN,NaN,NaN,NaN
1,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name
2,1,Samastipur,1,Samastipur,Raghunathpur
3,1,Samastipur,2,Samastipur,Barbatta
4,1,Samastipur,3,Rosra,Thahara Baijnathpur

In [179]:
data_BH = data_BH.iloc[1:].reset_index(drop=True)

data_BH.columns = data_BH.iloc[0]

data_BH = data_BH.drop(0).reset_index(drop=True)

data_BH['State Name'] = 'Bihar'
data_BH['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [180]:
data_BH.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Samastipur,1,Samastipur,Raghunathpur,Bihar,2011-2014
1,1,Samastipur,2,Samastipur,Barbatta,Bihar,2011-2014
2,1,Samastipur,3,Rosra,Thahara Baijnathpur,Bihar,2011-2014
3,1,Madhubani,4,Jhanjharpur,Behat,Bihar,2011-2014
4,1,Madhubani,5,Jainagar,Dhaniapatti,Bihar,2011-2014

In [181]:
data_BH = data_BH.iloc[:44]

In [182]:
data_BH.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Samastipur,1,Samastipur,Raghunathpur,Bihar,2011-2014
1,1,Samastipur,2,Samastipur,Barbatta,Bihar,2011-2014
2,1,Samastipur,3,Rosra,Thahara Baijnathpur,Bihar,2011-2014
3,1,Madhubani,4,Jhanjharpur,Behat,Bihar,2011-2014
4,1,Madhubani,5,Jainagar,Dhaniapatti,Bihar,2011-2014

In [183]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_BH.columns = new_column_names

### 4. Jharkhand

In [184]:
data_JH = pd.read_excel('P2011-14.xls', sheet_name=2)

In [185]:
data_JH.head()

,Districts and Tehsils of Bihar and Jharkhand for block period 2011-14,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Bihar,NaN,NaN,NaN,NaN
1,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name
2,1,Samastipur,1,Samastipur,Raghunathpur
3,1,Samastipur,2,Samastipur,Barbatta
4,1,Samastipur,3,Rosra,Thahara Baijnathpur

In [186]:
data_JH = data_JH.iloc[47:]

In [187]:
data_JH.head()

,Districts and Tehsils of Bihar and Jharkhand for block period 2011-14,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
47,NaN,NaN,NaN,NaN,NaN
48,Jharkhand,NaN,NaN,NaN,NaN
49,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name
50,1,Deoghar,1,Deoghar,Janakpur
51,1,Deoghar,2,Deoghar,Chakarana

In [188]:
data_JH = data_JH.iloc[2:].reset_index(drop=True)

data_JH.columns = data_JH.iloc[0]

data_JH = data_JH.drop(0).reset_index(drop=True)

data_JH['State Name'] = 'Jharkhand'
data_JH['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [189]:
data_JH.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Deoghar,1,Deoghar,Janakpur,Jharkhand,2011-2014
1,1,Deoghar,2,Deoghar,Chakarana,Jharkhand,2011-2014
2,1,Dumka,3,Dumka,Pokhariya,Jharkhand,2011-2014
3,1,Jamtara,4,Jamtara,Udalbanni,Jharkhand,2011-2014
4,1,Hazaribag,5,Hazaribag,Mehashwara,Jharkhand,2011-2014

In [190]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_JH.columns = new_column_names

### 5. Gujarat

In [191]:
data_GJ = pd.read_excel('P2011-14.xls', sheet_name=3)

In [192]:
data_GJ.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,Gujarat- List of Clusters for the Block Period...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Zone No,District Name,Tehsil Code,Tehsil Name,Village
3,NaN,1,Tapi,1,Songarh,Mandal
4,NaN,1,Tapi,2,Valod,Delwada

In [193]:
data_GJ = data_GJ.drop(data_GJ.columns[0], axis=1)

In [194]:
data_GJ.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Gujarat- List of Clusters for the Block Period...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Zone No,District Name,Tehsil Code,Tehsil Name,Village
3,1,Tapi,1,Songarh,Mandal
4,1,Tapi,2,Valod,Delwada

In [195]:
data_GJ = data_GJ.iloc[2:].reset_index(drop=True)

data_GJ.columns = data_GJ.iloc[0]

data_GJ = data_GJ.drop(0).reset_index(drop=True)

data_GJ['State Name'] = 'Gujarat'
data_GJ['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [196]:
data_GJ.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village,State Name,Year
0,1,Tapi,1,Songarh,Mandal,Gujarat,2011-2014
1,1,Tapi,2,Valod,Delwada,Gujarat,2011-2014
2,2,Narmada,3,Nadod,Rundh,Gujarat,2011-2014
3,2,Bharuch,4,Valia,Pathar,Gujarat,2011-2014
4,3,Vadodara,5,Sankheda,Gola Gamdi,Gujarat,2011-2014

In [197]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_GJ.columns = new_column_names

### 6. Himachal Pradesh

In [198]:
data_HP = pd.read_excel('P2011-14.xls', sheet_name=4)

In [199]:
data_HP.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,"H.P. University, Shimla-5.",NaN,NaN,NaN,NaN
1,NaN,NaN,Sampling for the crop complex year 2011-14,NaN,NaN,NaN
2,NaN,Sub : Sampling for the crop complex year 2011...,NaN,NaN,NaN,NaN
3,NaN,Zone,Tehsil (Nos.),Tehsil,District,Cluster Village
4,NaN,NaN,1,Chamba,Chamba,1.Nanu

In [200]:
data_HP = data_HP.drop(data_HP.columns[0], axis=1)

In [201]:
data_HP.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,"H.P. University, Shimla-5.",NaN,NaN,NaN,NaN
1,NaN,Sampling for the crop complex year 2011-14,NaN,NaN,NaN
2,Sub : Sampling for the crop complex year 2011...,NaN,NaN,NaN,NaN
3,Zone,Tehsil (Nos.),Tehsil,District,Cluster Village
4,NaN,1,Chamba,Chamba,1.Nanu

In [202]:
data_HP = data_HP.iloc[3:].reset_index(drop=True)

data_HP.columns = data_HP.iloc[0]

data_HP = data_HP.drop(0).reset_index(drop=True)

data_HP['State Name'] = 'Himachal Pradesh'
data_HP['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [203]:
data_HP.head()

,Zone,Tehsil (Nos.),Tehsil,District,Cluster Village,State Name,Year
0,NaN,1,Chamba,Chamba,1.Nanu,Himachal Pradesh,2011-2014
1,NaN,NaN,NaN,NaN,2.Sarol,Himachal Pradesh,2011-2014
2,I,2,Churah,Chamba,1.Gwari,Himachal Pradesh,2011-2014
3,NaN,NaN,NaN,NaN,2.Salahan,Himachal Pradesh,2011-2014
4,NaN,NaN,NaN,NaN,3.Kuther,Himachal Pradesh,2011-2014

In [204]:
data_HP = data_HP.ffill()

In [205]:
data_HP.head()

,Zone,Tehsil (Nos.),Tehsil,District,Cluster Village,State Name,Year
0,NaN,1,Chamba,Chamba,1.Nanu,Himachal Pradesh,2011-2014
1,NaN,1,Chamba,Chamba,2.Sarol,Himachal Pradesh,2011-2014
2,I,2,Churah,Chamba,1.Gwari,Himachal Pradesh,2011-2014
3,I,2,Churah,Chamba,2.Salahan,Himachal Pradesh,2011-2014
4,I,2,Churah,Chamba,3.Kuther,Himachal Pradesh,2011-2014

In [206]:
index_to_drop = [38, 83]
data_HP = data_HP.drop(index_to_drop)

In [207]:
data_HP.head()

,Zone,Tehsil (Nos.),Tehsil,District,Cluster Village,State Name,Year
0,NaN,1,Chamba,Chamba,1.Nanu,Himachal Pradesh,2011-2014
1,NaN,1,Chamba,Chamba,2.Sarol,Himachal Pradesh,2011-2014
2,I,2,Churah,Chamba,1.Gwari,Himachal Pradesh,2011-2014
3,I,2,Churah,Chamba,2.Salahan,Himachal Pradesh,2011-2014
4,I,2,Churah,Chamba,3.Kuther,Himachal Pradesh,2011-2014

In [208]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',  'Village', 'State Name', 'Year']

data_HP.columns = new_column_names

In [209]:
data_HP[['District Name', 'Tehsil Code']] = data_HP[['Tehsil Code', 'District Name']]

In [210]:
data_HP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village,State Name,Year
0,NaN,Chamba,1,Chamba,1.Nanu,Himachal Pradesh,2011-2014
1,NaN,Chamba,1,Chamba,2.Sarol,Himachal Pradesh,2011-2014
2,I,Churah,2,Chamba,1.Gwari,Himachal Pradesh,2011-2014
3,I,Churah,2,Chamba,2.Salahan,Himachal Pradesh,2011-2014
4,I,Churah,2,Chamba,3.Kuther,Himachal Pradesh,2011-2014

In [211]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_HP.columns = new_column_names

In [212]:
data_HP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,NaN,Chamba,1,Chamba,1.Nanu,Himachal Pradesh,2011-2014
1,NaN,Chamba,1,Chamba,2.Sarol,Himachal Pradesh,2011-2014
2,I,Churah,2,Chamba,1.Gwari,Himachal Pradesh,2011-2014
3,I,Churah,2,Chamba,2.Salahan,Himachal Pradesh,2011-2014
4,I,Churah,2,Chamba,3.Kuther,Himachal Pradesh,2011-2014

### 7. Haryana

In [213]:
data_Haryana = pd.read_excel('P2011-14.xls', sheet_name=5)

In [214]:
data_Haryana.head()

,"Format-II - Detail for Zone, District, Tehsil, Village Selected for the Block Period",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,2011-2014 under Cost of Cultivation Scheme (Ha...,NaN,NaN,NaN,NaN
1,Zone No.,District Name,Tehsil Code,Tehsil Name,Village Name
2,1,Bhiwani,1,Bhiwani,Maneharu
3,1,Bhiwani,2,Siwani,Dhulkot
4,1,Rewari,3,Rewari,Hasaka

In [215]:
data_Haryana = data_Haryana.iloc[1:].reset_index(drop=True)

data_Haryana.columns = data_Haryana.iloc[0]

data_Haryana = data_Haryana.drop(0).reset_index(drop=True)

data_Haryana['State Name'] = 'Haryana'
data_Haryana['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [216]:
data_Haryana.head()

,Zone No.,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Bhiwani,1,Bhiwani,Maneharu,Haryana,2011-2014
1,1,Bhiwani,2,Siwani,Dhulkot,Haryana,2011-2014
2,1,Rewari,3,Rewari,Hasaka,Haryana,2011-2014
3,1,Rewari,4,Bawal,Tihara,Haryana,2011-2014
4,1,Bhiwani,5,Charkhi Dadri,Fatehgarh,Haryana,2011-2014

In [217]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_Haryana.columns = new_column_names

### 8. Karnataka

In [218]:
data_Karnataka = pd.read_excel('P2011-14.xls', sheet_name=6)

In [219]:
data_Karnataka.head()

,Zone Name & Number,District Name,Tehsil Code,Tehsil Name,Village Name
0,I-North Eastern Transitinal Zone (NETZ),Bidar,1,Aurad,Rakshal (B)
1,NaN,NaN,2,Basavakalyan,Rajoi
2,NaN,Gulbarga,3,Aland,Rudrawadi
3,II- North Eastern Dry Zone (NEDZ),Yadagiri,4,shahapur,Doranahalli
4,NaN,NaN,5,Shorapur,Kavadimatti

In [220]:
data_Karnataka = data_Karnataka.ffill()

In [221]:
data_Karnataka.head()

,Zone Name & Number,District Name,Tehsil Code,Tehsil Name,Village Name
0,I-North Eastern Transitinal Zone (NETZ),Bidar,1,Aurad,Rakshal (B)
1,I-North Eastern Transitinal Zone (NETZ),Bidar,2,Basavakalyan,Rajoi
2,I-North Eastern Transitinal Zone (NETZ),Gulbarga,3,Aland,Rudrawadi
3,II- North Eastern Dry Zone (NEDZ),Yadagiri,4,shahapur,Doranahalli
4,II- North Eastern Dry Zone (NEDZ),Yadagiri,5,Shorapur,Kavadimatti

In [222]:
data_Karnataka['State Name'] = 'Karnataka'
data_Karnataka['Year'] = '2011-2014'

In [223]:
data_Karnataka.columns

Index(['Zone Name & Number ', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [224]:
data_Karnataka['Zone No'] = data_Karnataka['Zone Name & Number '].str.extract(r'^(I{1,3}|IV|V{1,3})')

# Drop the original "Zone Name and Number" column
data_Karnataka = data_Karnataka.drop(columns=['Zone Name & Number '])

In [225]:
data_Karnataka.head()

,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year,Zone No
0,Bidar,1,Aurad,Rakshal (B),Karnataka,2011-2014,I
1,Bidar,2,Basavakalyan,Rajoi,Karnataka,2011-2014,I
2,Gulbarga,3,Aland,Rudrawadi,Karnataka,2011-2014,I
3,Yadagiri,4,shahapur,Doranahalli,Karnataka,2011-2014,II
4,Yadagiri,5,Shorapur,Kavadimatti,Karnataka,2011-2014,II

In [226]:
desired_order = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']
data_Karnataka = data_Karnataka[desired_order]

### 9. Kerala

In [227]:
data_Kerala = pd.read_excel('P2011-14.xls', sheet_name=7)

In [228]:
data_Kerala.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Details of selected villages of Study on Cost ...,NaN,NaN,NaN,NaN
2,NaN,for the Block period 2011-14,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,For the purpose of the Study on Cost of Cultiv...,NaN,NaN,NaN,NaN

In [229]:
data_Kerala = data_Kerala.iloc[8:].reset_index(drop=True)

data_Kerala.columns = data_Kerala.iloc[0]

data_Kerala = data_Kerala.drop(0).reset_index(drop=True)

data_Kerala['State Name'] = 'Kerala'
data_Kerala['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [230]:
data_Kerala.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Alappuzha,1,Kuttanad,Kavalam,Kerala,2011-2014
1,1,Alappuzha,2,Kuttanad,Neelampeerur,Kerala,2011-2014
2,1,Kottayam,3,Vaikom,Kallara,Kerala,2011-2014
3,1,Thrissur,4,Chavakkad,Venkidangu,Kerala,2011-2014
4,2,Thiruvananthapuram,5,Neyyattinkara,Kulathur,Kerala,2011-2014

### 10. Maharastra

In [231]:
data_MH = pd.read_excel('P2011-14.xls', sheet_name=8)

In [232]:
data_MH.head()

,"Comprehensive Scheme, Department of Agril Economics,",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,"MPKV, Rahuri, Dist- Ahmednagar.(Maharashtra)",NaN,NaN,NaN,NaN
1,Block Period 2011-14,NaN,NaN,NaN,NaN
2,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name
3,I,Ratnagiri,1,Chiplun,Shirgaon
4,III,Thane,2,Mokhada,Morchondi

In [233]:
data_MH = data_MH.iloc[2:].reset_index(drop=True)

data_MH.columns = data_MH.iloc[0]

data_MH = data_MH.drop(0).reset_index(drop=True)

data_MH['State Name'] = 'Maharastra'
data_MH['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [234]:
data_MH.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,I,Ratnagiri,1,Chiplun,Shirgaon,Maharastra,2011-2014
1,III,Thane,2,Mokhada,Morchondi,Maharastra,2011-2014
2,IV,Satara,3,Patan,Nisre,Maharastra,2011-2014
3,IV,Pune,4,Khed,Shel Pimpalgaon,Maharastra,2011-2014
4,V,Pune,5,Junnar,Shiroli Bk.,Maharastra,2011-2014

In [235]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_Haryana.columns = new_column_names

### 11. Madhya Pradesh

In [236]:
data_MP = pd.read_excel('P2011-14.xls', sheet_name=9)

In [237]:
data_MP.head(9)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DEPARTMENT OF AGRICULTURAL ECONOMICS,NaN,NaN,NaN,NaN,NaN,NaN
1,AND FARM MANAGEMENT JNKVV JABALPUR,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CROP COMPLEX YEAR – (2011-2014),NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MADHYA PRADESH (STATE CODE - 09),NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"LIST OF SELECTED DISTRICT, TEHSIL AND VILLAGES",NaN,NaN,NaN,NaN,NaN,NaN
8,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,NaN,NaN

In [238]:
data_MP = data_MP.iloc[8:].reset_index(drop=True)

data_MP.columns = data_MP.iloc[0]

data_MP = data_MP.drop(0).reset_index(drop=True)

data_MP['State Name'] = 'Madhya Pradesh'
data_MP['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [239]:
data_MP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,NaN,NaN,State Name,Year
0,1,Bhind,1,Bhind,Pidoura,NaN,NaN,Madhya Pradesh,2011-2014
1,1,Maureina,2,Jora (Pahargarh),Chhaira,NaN,NaN,Madhya Pradesh,2011-2014
2,2,Shivpuri,3,Badarwar,Sumeila,NaN,NaN,Madhya Pradesh,2011-2014
3,2,Datia,4,Datia,Uprai,NaN,NaN,Madhya Pradesh,2011-2014
4,2,Guna,5,Raghavgarh,Aavan,NaN,NaN,Madhya Pradesh,2011-2014

In [240]:
data_MP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,NaN,NaN,State Name,Year
0,1,Bhind,1,Bhind,Pidoura,NaN,NaN,Madhya Pradesh,2011-2014
1,1,Maureina,2,Jora (Pahargarh),Chhaira,NaN,NaN,Madhya Pradesh,2011-2014
2,2,Shivpuri,3,Badarwar,Sumeila,NaN,NaN,Madhya Pradesh,2011-2014
3,2,Datia,4,Datia,Uprai,NaN,NaN,Madhya Pradesh,2011-2014
4,2,Guna,5,Raghavgarh,Aavan,NaN,NaN,Madhya Pradesh,2011-2014

In [241]:
data_MP.columns = data_MP.columns.fillna('to_drop')
data_MP.drop('to_drop', axis = 1, inplace = True)

In [242]:
data_MP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Bhind,1,Bhind,Pidoura,Madhya Pradesh,2011-2014
1,1,Maureina,2,Jora (Pahargarh),Chhaira,Madhya Pradesh,2011-2014
2,2,Shivpuri,3,Badarwar,Sumeila,Madhya Pradesh,2011-2014
3,2,Datia,4,Datia,Uprai,Madhya Pradesh,2011-2014
4,2,Guna,5,Raghavgarh,Aavan,Madhya Pradesh,2011-2014

In [243]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_MP.columns = new_column_names

In [244]:
data_MP = data_MP.dropna()

In [245]:
data_MP.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Bhind,1,Bhind,Pidoura,Madhya Pradesh,2011-2014
1,1,Maureina,2,Jora (Pahargarh),Chhaira,Madhya Pradesh,2011-2014
2,2,Shivpuri,3,Badarwar,Sumeila,Madhya Pradesh,2011-2014
3,2,Datia,4,Datia,Uprai,Madhya Pradesh,2011-2014
4,2,Guna,5,Raghavgarh,Aavan,Madhya Pradesh,2011-2014

### 12. Chhattisgarh

In [246]:
data_Chh = pd.read_excel('P2011-14.xls', sheet_name=10)

In [247]:
data_Chh.head()

,COST OF CULTIVATION SCHEME,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,DEPARTMENT OF AGRICULTURAL ECONOMICS,NaN,NaN,NaN,NaN
1,AND FARM MANAGEMENT JNKVV JABALPUR,NaN,NaN,NaN,NaN
2,CROP COMPLEX YEAR – (2011-2014),NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,CHHATTISGARH (STATE CODE - 19),NaN,NaN,NaN,NaN

In [248]:
data_Chh = data_Chh.iloc[7:].reset_index(drop=True)

data_Chh.columns = data_Chh.iloc[0]

data_Chh = data_Chh.drop(0).reset_index(drop=True)

data_Chh['State Name'] = 'Chhattisgarh'
data_Chh['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [249]:
data_Chh.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Raigarh,1,Gharghora,Teram,Chhattisgarh,2011-2014
1,1,Korba,2,Korba,Semipali,Chhattisgarh,2011-2014
2,1,Bilaspur,3,Mustari,Itva,Chhattisgarh,2011-2014
3,1,Janjgeer,4,Dabra,Devarghat,Chhattisgarh,2011-2014
4,1,Jashpur,5,Pathalgaon,Shivpur,Chhattisgarh,2011-2014

### 13. Odisha

In [250]:
data_Odd = pd.read_excel('P2011-14.xls', sheet_name=11)

In [251]:
data_Odd.head()

,Information Of Odisha to be Posted on the Web-site of the DES,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,...,NaN,NaN,NaN,NaN
1,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name
2,1,Balasore,1,Jaleswar,Bartana
3,1,Balasore,2,Balasore,Chhanua
4,1,Bhadrak,3,Chandbali,Nandapur

In [252]:
data_Odd = data_Odd.iloc[1:].reset_index(drop=True)

data_Odd.columns = data_Odd.iloc[0]

data_Odd = data_Odd.drop(0).reset_index(drop=True)

data_Odd['State Name'] = 'Odisha'
data_Odd['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [253]:
data_Odd.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,1,Balasore,1,Jaleswar,Bartana,Odisha,2011-2014
1,1,Balasore,2,Balasore,Chhanua,Odisha,2011-2014
2,1,Bhadrak,3,Chandbali,Nandapur,Odisha,2011-2014
3,1,Cuttack,4,Nischintakoili,Patpur,Odisha,2011-2014
4,1,Cuttack,5,Salepur,Satyabhamapur,Odisha,2011-2014

### 14. Punjab

In [254]:
data_Pb = pd.read_excel('P2011-14.xls', sheet_name=12)

In [255]:
data_Pb.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Information,for the block,period 2011-14,"Punjab Agricultural University, Ludhiana",NaN
1,NaN,NaN,NaN,NaN,NaN
2,Zone No,District Name,Tehsil,Tehsil,Village Name
3,NaN,NaN,Code,Name,NaN
4,I,Gurdaspur,1,Gurdaspur,Shaikha

In [256]:
data_Pb = data_Pb.iloc[2:].reset_index(drop=True)

data_Pb.columns = data_Pb.iloc[0]

data_Pb = data_Pb.drop(0).reset_index(drop=True)

data_Pb['State Name'] = 'Punjab'
data_Pb['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [257]:
data_Pb.head()

,Zone No,District Name,Tehsil,Tehsil,Village Name,State Name,Year
0,NaN,NaN,Code,Name,NaN,Punjab,2011-2014
1,I,Gurdaspur,1,Gurdaspur,Shaikha,Punjab,2011-2014
2,NaN,Gurdaspur,2,Batala,Bojha,Punjab,2011-2014
3,NaN,Amrtisar,3,Amritsar-II,Pandori Wraich,Punjab,2011-2014
4,NaN,Tarntaean,4,Patti,Kairon,Punjab,2011-2014

In [258]:
data_Pb = data_Pb.ffill()

In [259]:
data_Pb.head()

,Zone No,District Name,Tehsil,Tehsil,Village Name,State Name,Year
0,NaN,NaN,Code,Name,NaN,Punjab,2011-2014
1,I,Gurdaspur,1,Gurdaspur,Shaikha,Punjab,2011-2014
2,I,Gurdaspur,2,Batala,Bojha,Punjab,2011-2014
3,I,Amrtisar,3,Amritsar-II,Pandori Wraich,Punjab,2011-2014
4,I,Tarntaean,4,Patti,Kairon,Punjab,2011-2014

In [260]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_Pb.columns = new_column_names

### 15. Rajasthan

In [261]:
data_RJ = pd.read_excel('P2011-14.xls', sheet_name=13)

In [262]:
data_RJ.head()

,Cost of Cultivation Studies,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,"MPUAT, Udaipur",NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,Summary Data for the block Period 2011-14,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,Zone No.,District Name,Tehsil Code,Tehsil Name,Village Name

In [263]:
data_RJ = data_RJ.iloc[4:].reset_index(drop=True)

data_RJ.columns = data_RJ.iloc[0]

data_RJ = data_RJ.drop(0).reset_index(drop=True)

data_RJ['State Name'] = 'Rajasthan'
data_RJ['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [264]:
data_RJ.head()

,Zone No.,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,I,NaN,NaN,NaN,NaN,Rajasthan,2011-2014
1,,Jodhpur,1,Shergarh,Sai,Rajasthan,2011-2014
2,NaN,Jodhpur,2,Shergarh,Kherja Tibna,Rajasthan,2011-2014
3,NaN,Barmer,3,Barmer,Jasai,Rajasthan,2011-2014
4,NaN,Jodhpur,4,Phalodi,Shekhasar,Rajasthan,2011-2014

In [265]:
data_RJ = data_RJ.ffill()

In [266]:
data_RJ.head()

,Zone No.,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,I,NaN,NaN,NaN,NaN,Rajasthan,2011-2014
1,,Jodhpur,1.0,Shergarh,Sai,Rajasthan,2011-2014
2,,Jodhpur,2.0,Shergarh,Kherja Tibna,Rajasthan,2011-2014
3,,Barmer,3.0,Barmer,Jasai,Rajasthan,2011-2014
4,,Jodhpur,4.0,Phalodi,Shekhasar,Rajasthan,2011-2014

In [267]:
data_RJ.loc[1:11, 'Zone No.'] = 'I'

In [268]:
data_RJ.head()

,Zone No.,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,I,NaN,NaN,NaN,NaN,Rajasthan,2011-2014
1,I,Jodhpur,1.0,Shergarh,Sai,Rajasthan,2011-2014
2,I,Jodhpur,2.0,Shergarh,Kherja Tibna,Rajasthan,2011-2014
3,I,Barmer,3.0,Barmer,Jasai,Rajasthan,2011-2014
4,I,Jodhpur,4.0,Phalodi,Shekhasar,Rajasthan,2011-2014

In [269]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_RJ.columns = new_column_names

### 16. Tamil Nadu

In [270]:
data_TN = pd.read_excel('P2011-14.xls', sheet_name=14)

In [271]:
data_TN.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,COMPREHENSIVE SCHEME FOR STUDYING THE C...,NaN,NaN,NaN,NaN
1,"Details of Zone, District, Tehsil, Villages Se...",NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,ZONE No.,DISTRICT NAME,TEHSIL CODE,TEHSIL NAME,VILLAGE NAME

In [272]:
data_TN = data_TN.iloc[4:].reset_index(drop=True)

data_TN.columns = data_TN.iloc[0]

data_TN = data_TN.drop(0).reset_index(drop=True)

data_TN['State Name'] = 'Tamil Nadu'
data_TN['Year'] = '2011-2014'

#data_AP = data_AP.dropna(axis=1, how='any')

In [273]:
data_TN.head()

,ZONE No.,DISTRICT NAME,TEHSIL CODE,TEHSIL NAME,VILLAGE NAME,State Name,Year
0,1,THIRUVALLUR,1,PONNERI,ANUPPAMPATTU-2,Tamil Nadu,2011-2014
1,1,THIRUVALLUR,2,THIRUVALLUR,VELLIYUR-1,Tamil Nadu,2011-2014
2,1,KANCHEEPURAM,3,KANCHEEPURAM,PURISAI,Tamil Nadu,2011-2014
3,2,VELLORE,4,GUDIYATHAM,KALLAPADI,Tamil Nadu,2011-2014
4,2,VELLORE,5,VELLORE,THELLUR,Tamil Nadu,2011-2014

In [274]:
index_to_drop = [25, 46]
data_TN = data_TN.drop(index_to_drop)

In [275]:
data_TN.head()

,ZONE No.,DISTRICT NAME,TEHSIL CODE,TEHSIL NAME,VILLAGE NAME,State Name,Year
0,1,THIRUVALLUR,1,PONNERI,ANUPPAMPATTU-2,Tamil Nadu,2011-2014
1,1,THIRUVALLUR,2,THIRUVALLUR,VELLIYUR-1,Tamil Nadu,2011-2014
2,1,KANCHEEPURAM,3,KANCHEEPURAM,PURISAI,Tamil Nadu,2011-2014
3,2,VELLORE,4,GUDIYATHAM,KALLAPADI,Tamil Nadu,2011-2014
4,2,VELLORE,5,VELLORE,THELLUR,Tamil Nadu,2011-2014

In [276]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_TN.columns = new_column_names

### 17. West Bengal

In [277]:
data_WB = pd.read_excel('P2011-14.xls', sheet_name=15)

In [278]:
data_WB.head(9)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Comprehensive Cost of Cultivation Scheme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"R.B.S.College,Bichpuri,Agra",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,"Name of Districts,Selected Tehsils and Village...",NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Zone,District,Tehsil,Tehsil,Selected Villages,NaN,NaN
5,NaN,NaN,no.,Name,Code,Name,Nucleus,South,Third
6,NaN,NaN,1,Rudra Prayag,1,Rudra Prayag,Nagrasu,Mabada,NaN
7,NaN,NaN,2,U.S.Nagar,2,Sitarganj,Darhaha,Malpuri,NaN
8,NaN,NaN,2,U.S.Nagar,3,Jaspur,Kishanpur,NaN,NaN

In [279]:
data_WB = data_WB.iloc[4:].reset_index(drop=True)

data_WB.columns = data_WB.iloc[0]

data_WB = data_WB.drop(0).reset_index(drop=True)

data_WB['State Name'] = 'West Bengal'
data_WB['Year'] = '2011-2014'

In [280]:
data_WB.head(7)

,NaN,NaN,Zone,District,Tehsil,Tehsil,Selected Villages,NaN,NaN,State Name,Year
0,NaN,NaN,no.,Name,Code,Name,Nucleus,South,Third,West Bengal,2011-2014
1,NaN,NaN,1,Rudra Prayag,1,Rudra Prayag,Nagrasu,Mabada,NaN,West Bengal,2011-2014
2,NaN,NaN,2,U.S.Nagar,2,Sitarganj,Darhaha,Malpuri,NaN,West Bengal,2011-2014
3,NaN,NaN,2,U.S.Nagar,3,Jaspur,Kishanpur,NaN,NaN,West Bengal,2011-2014
4,NaN,NaN,3,Haridwar,4,Haridwar,Bhogpur,NaN,NaN,West Bengal,2011-2014
5,NaN,NaN,2,Baharaich,5,Nanpara,Jagannathpur-purey,NaN,NaN,West Bengal,2011-2014
6,NaN,NaN,2,Khiri,6,Paliya,Badagaon,NaN,NaN,West Bengal,2011-2014

In [281]:
data_WB = data_WB.iloc[:, 2:]

In [282]:
data_WB.head(5)

,Zone,District,Tehsil,Tehsil,Selected Villages,NaN,NaN,State Name,Year
0,no.,Name,Code,Name,Nucleus,South,Third,West Bengal,2011-2014
1,1,Rudra Prayag,1,Rudra Prayag,Nagrasu,Mabada,NaN,West Bengal,2011-2014
2,2,U.S.Nagar,2,Sitarganj,Darhaha,Malpuri,NaN,West Bengal,2011-2014
3,2,U.S.Nagar,3,Jaspur,Kishanpur,NaN,NaN,West Bengal,2011-2014
4,3,Haridwar,4,Haridwar,Bhogpur,NaN,NaN,West Bengal,2011-2014

In [283]:
data_WB = data_WB.drop(index=0)

In [284]:
data_WB.head()

,Zone,District,Tehsil,Tehsil,Selected Villages,NaN,NaN,State Name,Year
1,1,Rudra Prayag,1,Rudra Prayag,Nagrasu,Mabada,NaN,West Bengal,2011-2014
2,2,U.S.Nagar,2,Sitarganj,Darhaha,Malpuri,NaN,West Bengal,2011-2014
3,2,U.S.Nagar,3,Jaspur,Kishanpur,NaN,NaN,West Bengal,2011-2014
4,3,Haridwar,4,Haridwar,Bhogpur,NaN,NaN,West Bengal,2011-2014
5,2,Baharaich,5,Nanpara,Jagannathpur-purey,NaN,NaN,West Bengal,2011-2014

In [285]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Selected Villages', 'Village II', 'Village III', 
                    'State Name', 'Year']

data_WB.columns = new_column_names

In [286]:
data_WB.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Selected Villages,Village II,Village III,State Name,Year
1,1,Rudra Prayag,1,Rudra Prayag,Nagrasu,Mabada,NaN,West Bengal,2011-2014
2,2,U.S.Nagar,2,Sitarganj,Darhaha,Malpuri,NaN,West Bengal,2011-2014
3,2,U.S.Nagar,3,Jaspur,Kishanpur,NaN,NaN,West Bengal,2011-2014
4,3,Haridwar,4,Haridwar,Bhogpur,NaN,NaN,West Bengal,2011-2014
5,2,Baharaich,5,Nanpara,Jagannathpur-purey,NaN,NaN,West Bengal,2011-2014

In [287]:
df_melted = data_WB.melt(
    id_vars=['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'State Name', 'Year'],
    value_vars=['Selected Villages', 'Village II', 'Village III'],
    var_name='Village Type',
    value_name='Village Name'
)

df_melted = df_melted.dropna(subset=['Village Name'])

df_melted = df_melted.drop(columns=['Village Type'])

df_melted = df_melted.reset_index(drop=True)

In [288]:
df_melted.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,State Name,Year,Village Name
0,1,Rudra Prayag,1,Rudra Prayag,West Bengal,2011-2014,Nagrasu
1,2,U.S.Nagar,2,Sitarganj,West Bengal,2011-2014,Darhaha
2,2,U.S.Nagar,3,Jaspur,West Bengal,2011-2014,Kishanpur
3,3,Haridwar,4,Haridwar,West Bengal,2011-2014,Bhogpur
4,2,Baharaich,5,Nanpara,West Bengal,2011-2014,Jagannathpur-purey

In [289]:
data_WB = df_melted[['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']]

In [290]:
new_column_names = ['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name', 'Village Name', 'State Name', 'Year']

data_WB.columns = new_column_names

## Integerating the Dataset

In [291]:
data_AP.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object', name=0)

In [292]:
data_Assam.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [293]:
data_BH.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [294]:
data_JH.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [295]:
data_GJ.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [296]:
data_HP.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [297]:
data_Haryana.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [298]:
data_Kerala.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object', name=0)

In [299]:
data_Chh.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object', name=0)

In [300]:
data_Odd.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object', name=0)

In [301]:
data_Pb.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [302]:
data_RJ.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [303]:
data_TN.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [304]:
data_WB.columns

Index(['Zone No', 'District Name', 'Tehsil Code', 'Tehsil Name',
       'Village Name', 'State Name', 'Year'],
      dtype='object')

In [305]:
dataframes = [data_AP, data_Assam, data_BH, data_JH, data_GJ, data_HP, data_Haryana, data_Kerala, data_Chh, data_Odd, 
              data_Pb, data_RJ, data_TN, data_WB, data_MP, data_Karnataka, data_MH]

merged_df = pd.concat(dataframes, ignore_index=True)

In [306]:
merged_df.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali,Andhra Pradesh,2011-2014
1,Zone -I,Srikakulam,2,Amdalavasa,Dusi,Andhra Pradesh,2011-2014
2,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru,Andhra Pradesh,2011-2014
3,Zone -I,Vishakapatnam,4,Makavara Palem,Byyavaram,Andhra Pradesh,2011-2014
4,Zone-II,East Godavari,5,Samalkota,J.Peta,Andhra Pradesh,2011-2014

In [307]:
merged_df.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali,Andhra Pradesh,2011-2014
1,Zone -I,Srikakulam,2,Amdalavasa,Dusi,Andhra Pradesh,2011-2014
2,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru,Andhra Pradesh,2011-2014
3,Zone -I,Vishakapatnam,4,Makavara Palem,Byyavaram,Andhra Pradesh,2011-2014
4,Zone-II,East Godavari,5,Samalkota,J.Peta,Andhra Pradesh,2011-2014

In [308]:
merged_df['State Name'].value_counts()

Assam               116
Himachal Pradesh    101
West Bengal          84
Rajasthan            70
Maharastra           62
Tamil Nadu           60
Andhra Pradesh       60
Gujarat              53
Odisha               45
Madhya Pradesh       45
Karnataka            45
Bihar                44
Punjab               31
Kerala               30
Haryana              30
Jharkhand            15
Chhattisgarh         15
Name: State Name, dtype: int64

In [311]:
merged_df.head()

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali,Andhra Pradesh,2011-2014
1,Zone -I,Srikakulam,2,Amdalavasa,Dusi,Andhra Pradesh,2011-2014
2,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru,Andhra Pradesh,2011-2014
3,Zone -I,Vishakapatnam,4,Makavara Palem,Byyavaram,Andhra Pradesh,2011-2014
4,Zone-II,East Godavari,5,Samalkota,J.Peta,Andhra Pradesh,2011-2014

In [312]:
merged_df = merged_df.dropna(subset=['Village Name'])

In [313]:
merged_df

,Zone No,District Name,Tehsil Code,Tehsil Name,Village Name,State Name,Year
0,Zone -I,Srikakulam,1,Vajrapukothur,Patha Tekkali,Andhra Pradesh,2011-2014
1,Zone -I,Srikakulam,2,Amdalavasa,Dusi,Andhra Pradesh,2011-2014
2,Zone -I,Vizianagaram.,3,Bondapalli,B.Rajeru,Andhra Pradesh,2011-2014
3,Zone -I,Vishakapatnam,4,Makavara Palem,Byyavaram,Andhra Pradesh,2011-2014
4,Zone-II,East Godavari,5,Samalkota,J.Peta,Andhra Pradesh,2011-2014
5,Zone-II,East Godavari,6,Biccavolu,Balabadhapuram.,Andhra Pradesh,2011-2014
6,Zone-II,East Godavari,7,Kajuluru,Kajuluru,Andhra Pradesh,2011-2014
7,Zone-II,East Godavari,8,Razole,Kadali,Andhra Pradesh,2011-2014
8,Zone-II,East Godavari,9,Katrenikona,Pallamkurru,Andhra Pradesh,2011-2014
9,Zone-II,West Godavari,10,Bhimadole,Polasanipalli,Andhra Pradesh,2011-2014
10,Zone-II,West Godavari,11,Denuduluru,Denuduluru,Andhra Pradesh,2011-2014
11,Zone-II,West Godavari,12,Pentapudu,Ravipadu,Andhra Pradesh,2011-2014
12,Zone-II,West Godavari,13,Veeravasaram,Veeravasaram,Andhra Pradesh,2011-2014
13,Zone-II,Krishna,14,Pedaparupudi,Ventrapragada,Andhra Pradesh,2011-2014
14,Zone-II,Krishna,15,Kankipadu,Tenneru,Andhra Pradesh,2011-2014
15,Zone-II,Guntur,16,Tsunduru,Edlapalli,Andhra Pradesh,2011-2014
16,Zone-II,Guntur,17,Nakirekal,Kunkalagunta,Andhra Pradesh,2011-2014
17,Zone-II,Guntur,18,Kollipara,Vallabbapuram,Andhra Pradesh,2011-2014
18,Zone-II,Guntur,19,Pedakakani,Takkellapadu,Andhra Pradesh,2011-2014
19,Zone-II,Prakasam,20,Pamur,Batlagudur,Andhra Pradesh,2011-2014
20,Zone-II,Nellore,21,Thotapalligudur,Thotapalligudur,Andhra Pradesh,2011-2014
21,Zone-III,Chittoor,22,Pitchatur,Mudiyuru,Andhra Pradesh,2011-2014
22,Zone-III,Chittoor,23,Narayanavanam,Aranyamkandriga,Andhra Pradesh,2011-2014
23,Zone-III,Chittoor,24,Palamaner,Moram,Andhra Pradesh,2011-2014
24,Zone-III,Chittoor,25,Irala .,Mudigalam,Andhra Pradesh,2011-2014
25,Zone-III,Chittoor,26,Ramasumudram,Chokkandapalli,Andhra Pradesh,2011-2014
26,Zone-III,Kadapa,27,Sundupalli,Madhitadu,Andhra Pradesh,2011-2014
27,Zone-III,Kadapa,28,Kajipet,Bhumayapalli,Andhra Pradesh,2011-2014
28,Zone-III,Kadapa,29,Vempalli,T.Vellmaripalli,Andhra Pradesh,2011-2014
29,Zone-III,Kadapa,30,Galliveedu,Noliveedu,Andhra Pradesh,2011-2014
30,Zone-III,Ananthapur,31,Beluguppa,Narasapuram,Andhra Pradesh,2011-2014
31,Zone-III,Ananthapur,32,Kothacheruvu,Bandapalli,Andhra Pradesh,2011-2014
32,Zone-III,Kurnool,33,Midthur,Talamudipi,Andhra Pradesh,2011-2014
33,Zone-III,Kurnool,34,Nandavaram,Somalagudur,Andhra Pradesh,2011-2014
34,Zone-III,Kurnool,35,Kolimigundla,Nandipadu,Andhra Pradesh,2011-2014
35,Zone-IV,Mahaboobnagar,36,Talakondapalli,Veljal,Andhra Pradesh,2011-2014
36,Zone-IV,Mahaboobnagar,37,Jadcherla,Polepalli,Andhra Pradesh,2011-2014
37,Zone-IV,Mahaboobnagar,38,Manopad,Undavelly,Andhra Pradesh,2011-2014
38,Zone-IV,Ranga Reddy,39,Mominpet,Velchal,Andhra Pradesh,2011-2014
39,Zone-IV,Ranga Reddy,40,Shankarpalli,Tangutoor,Andhra Pradesh,2011-2014
40,Zone-IV,Ranga Reddy,41,Shabad,Soli Pet,Andhra Pradesh,2011-2014
41,Zone-IV,Khammam,42,Yerrupalem,Takkellapadu,Andhra Pradesh,2011-2014
42,Zone-IV,Khammam,43,Vemsoor,Vemsoor,Andhra Pradesh,2011-2014
43,Zone-IV,Nalgonda,44,Kattangoor,Aitipamala,Andhra Pradesh,2011-2014
44,Zone-IV,Nalgonda,45,Bhovangiri,Surepalli,Andhra Pradesh,2011-2014
45,Zone-IV,Nalgonda,46,Kangal,Kangal,Andhra Pradesh,2011-2014
46,Zone-V,Medak,47,Chinnakodur,Allipur,Andhra Pradesh,2011-2014
47,Zone-V,Medak,48,Kondapak,Kondapak,Andhra Pradesh,2011-2014
48,Zone-V,Medak,49,Jinnaram,Gummadidala,Andhra Pradesh,2011-2014
49,Zone-V,Medak,50,Siddipet,Narayanaropet,Andhra Pradesh,2011-2014
50,Zone-V,Nizamabad,51,Nizamabad,Nyalkal,Andhra Pradesh,2011-2014
51,Zone-V,Nizamabad,52,Sadasiva Nagar,Kupriyal,Andhra Pradesh,2011-2014
52,Zone-V,Nizamabad,53,Pitlam,Pitlam,Andhra Pradesh,2011-2014
53,Zone-V,Adilabad,54,Kubeer,Kubeer,Andhra Pradesh,2011-2014
54,Zone-V,Karimnagar,55,Kamanpur,Begumpet,Andhra Pradesh,2011-2014
55,Zone-V,Karimnagar,56,Julapalli,Julapalli,Andhra Pradesh,2011-2014
56,Zone-V,Karminagar,57,Chigurumamidi,Rekonda,Andhra Pradesh,2011-2014
57,Zone-V,Karimnagar,58,Choppadandi,Choppadandi,Andhra Pradesh,2011-2014
58,Zone-V,Warangal,59,Jangoan,Ganugupahad,Andhra Pradesh,2011-2014
59,Zone-V,Warangal,60,Wardhannapet,Ellanda,Andhra Pradesh,2011-2014
60,I,Dhemaji,1,Dhemaji,Ghilaguri,Assam,2011-2014
61,I,Dhemaji,1,Dhemaji,Gualgaon,Assam,2011-2014
62,I,Dhemaji,1,Dhemaji,Nagaon,Assam,2011-2014
63,I,Lakhimpur,2,North Lakhimpur,Hatilung,Assam,2011-2014
64,I,Lakhimpur,2,North Lakhimpur,Bogalijan,Assam,2011-2014
65,I,Lakhimpur,2,North Lakhimpur,Bowalguri,Assam,2011-2014
66,I,Sonitpur,3,Chariduar,Khonamukh,Assam,2011-2014
67,I,Sonitpur,3,Chariduar,Rajgarh,Assam,2011-2014
68,I,Sonitpur,4,Dhekiajuli,Bamun pukhuri-II,Assam,2011-2014
69,I,Sonitpur,4,Dhekiajuli,Patia pukhuri,Assam,2011-2014
70,I,Sonitpur,4,Dhekiajuli,Baryati,Assam,2011-2014
71,I,Sonitpur,5,Tezpur Sadar,Likhak Gaon,Assam,2011-2014
72,I,Sonitpur,5,Tezpur Sadar,Bhaluke Khowa,Assam,2011-2014
73,I,Sonitpur,5,Tezpur Sadar,Latamara,Assam,2011-2014
74,I,Darrang,6,Dalgaon,Balogara,Assam,2011-2014
75,I,Darrang,6,Dalgaon,Niz Kharupetia,Assam,2011-2014
76,I,Darrang,6,Dalgaon,3 No. Thekerabari,Assam,2011-2014
77,I,Udalguri,7,Mazbat,Nisalamari,Assam,2011-2014
78,I,Udalguri,7,Mazbat,Samuagaon,Assam,2011-2014
79,I,Udalguri,7,Mazbat,Garubandha,Assam,2011-2014
80,II,Sibsagar,8,Amguri,Hatimuria gaon,Assam,2011-2014
81,II,Sibsagar,8,Amguri,Deodhai gaon,Assam,2011-2014
82,II,Sibsagar,9,Sibsagar,Charing Baruaty,Assam,2011-2014
83,II,Sibsagar,9,Sibsagar,Duliagaon,Assam,2011-2014
84,II,Sibsagar,9,Sibsagar,Nathgaon,Assam,2011-2014
85,II,Jorhat,10,Teok,Bon Pithaguri,Assam,2011-2014
86,II,Jorhat,10,Teok,Noragaon,Assam,2011-2014
87,II,Jorhat,11,Majuli,Dhekiajuli,Assam,2011-2014
88,II,Jorhat,11,Majuli,Mohkina,Assam,2011-2014
89,II,Jorhat,12,Jorhat East,Pujari Gaon,Assam,2011-2014
90,II,Jorhat,12,Jorhat East,Balichapori Bahat gaon,Assam,2011-2014
91,II,Jorhat,12,Jorhat East,Borkhat gaon,Assam,2011-2014
92,II,Jorhat,13,Jorhat West,Dhan Khulai,Assam,2011-2014
93,II,Jorhat,13,Jorhat West,2.Nos. Deorigaon,Assam,2011-2014
94,II,Jorhat,13,Jorhat West,Chengliati,Assam,2011-2014
95,II,Jorhat,14,Titabar,Pathar Shyam Gaon,Assam,2011-2014
96,II,Jorhat,14,Titabar,Silikhabari,Assam,2011-2014
97,II,Golaghat,15,Dergaon,Bilotia,Assam,2011-2014
98,II,Golaghat,15,Dergaon,Dhemaji Koibarta,Assam,2011-2014
99,II,Golaghat,15,Dergaon,Dhemaji Koibarta(East),Assam,2011-2014
100,II,Golaghat,16,Golaghat Sadar,Dagohain,Assam,2011-2014
101,II,Golaghat,16,Golaghat Sadar,Mout gaon,Assam,2011-2014
102,II,Golaghat,17,Numali-garh,Panka Pathar,Assam,2011-2014
103,II,Golaghat,17,Numali-garh,Panka No.1,Assam,2011-2014
104,II,Golaghat,18,Sarupa-thar,Chewaguri,Assam,2011-2014
105,II,Golaghat,18,Sarupa-thar,Dhansiripathar,Assam,2011-2014
106,II,Golaghat,19,Khumtai,Chetiagaon,Assam,2011-2014
107,II,Golaghat,19,Khumtai,Sensowa,Assam,2011-2014
108,II,Dibru-garh,20,Dibru-garh,Jakai Harok Pathar,Assam,2011-2014
109,II,Dibru-garh,20,Dibru-garh,Dihing Tekerani gaon,Assam,2011-2014
110,II,Dibru-garh,20,Dibru-garh,Jakai Konwar gaon,Assam,2011-2014
111,III,Nagaon,21,Sadar (Nagaon),Dakarghat Jarani,Assam,2011-2014
112,III,Nagaon,21,Sadar (Nagaon),N. Bebejia,Assam,2011-2014
113,III,Nagaon,22,Lanka,Thaisupar-5,Assam,2011-2014
114,III,Nagaon,22,Lanka,Pathari-5,Assam,2011-2014
115,III,Nagaon,22,Lanka,Mudoiyani-5,Assam,2011-2014
116,III,Nagaon,23,Sama-guri,Chalchali Birahigaon,Assam,2011-2014
117,III,Nagaon,23,Sama-guri,Jalahgaon,Assam,2011-2014
118,III,Nagaon,24,Kaliabor,Hatborgaon,Assam,2011-2014
119,III,Nagaon,24,Kaliabor,Borigaon,Assam,2011-2014
120,III,Nagaon,24,Kaliabor,Sundargaon,Assam,2011-2014
121,III,Morigaon,25,Moira-bari,Boza Khatigaon,Assam,2011-2014
122,III,Morigaon,25,Moira-bari,Boza Khati Pathar,Assam,2011-2014
123,III,Morigaon,25,Moira-bari,Borchapori,Assam,2011-2014
124,III,Morigaon,26,Mikir-bheta,Bor Monipur,Assam,2011-2014
125,III,Morigaon,26,Mikir-bheta,Parghali gaon,Assam,2011-2014
126,III,Morigaon,26,Mikir-bheta,Suta Monipur,Assam,2011-2014
127,IV,Kamrup,27,Chandrapur,Thakurkuchi-I,Assam,2011-2014
128,IV,Kamrup,27,Chandrapur,Thakurkuchi-II,Assam,2011-2014
129,IV,Kamrup,27,Chandrapur,Thakurkuchi-Non cay,Assam,2011-2014
130,IV,Kamrup,28,Rangia,Barmura,Assam,2011-2014
131,IV,Kamrup,28,Rangia,Sandhiya,Assam,2011-2014
132,IV,Kamrup,29,Palashbari,Dahali,Assam,2011-2014
133,IV,Nalbari,30,East Nalbari,Nankarvaira,Assam,2011-2014
134,IV,Nalbari,30,East Nalbari,Shahpur,Assam,2011-2014
135,IV,Nalbari,30,East Nalbari,Jaijabari,Assam,2011-2014
136,IV,Nalbari,31,Borbhag,Arikuchi,Assam,2011-2014
137,IV,Nalbari,31,Borbhag,Morowa,Assam,2011-2014
138,IV,Barpeta,32,Chenga,Batgaon,Assam,2011-2014
139,IV,Barpeta,32,Chenga,Ganakpara,Assam,2011-2014
140,IV,Barpeta,32,Chenga,Kadamtala,Assam,2011-2014
141,IV,Barpeta,33,Barnagar,Dhupguri,Assam,2011-2014
142,IV,Barpeta,33,Barnagar,Raipur,Assam,2011-2014
143,IV,Baksa,34,Tamulpur,Majdia,Assam,2011-2014
144,IV,Baksa,34,Tamulpur,Kahibari,Assam,2011-2014
145,IV,Baksa,34,Tamulpur,Balabari,Assam,2011-2014
146,IV,Bongaigaon,35,Bongaigaon,Yogipara,Assam,2011-2014
147,IV,Bongaigaon,35,Bongaigaon,Bhatipara,Assam,2011-2014
148,IV,Bongaigaon,35,Bongaigaon,Bakhrapara,Assam,2011-2014
149,IV,Chirang,36,Chidly,Oujani,Assam,2011-2014
150,IV,Chirang,36,Chidly,Purba- Ankarbari,Assam,2011-2014
151,IV,Chirang,36,Chidly,Debargaon,Assam,2011-2014
152,IV,Goalpara,37,Balijana,Bhoiskhuli,Assam,2011-2014
153,IV,Goalpara,37,Balijana,Doshrapara,Assam,2011-2014
154,IV,Goalpara,37,Balijana,Kurua-bhasa,Assam,2011-2014
155,IV,Kokrajhar,38,Dotma,Silipota,Assam,2011-2014
156,IV,Kokrajhar,38,Dotma,Jodumoni,Assam,2011-2014
157,IV,Kokrajhar,38,Dotma,Mukhigaon,Assam,2011-2014
158,IV,Dhubri,39,Dhubri- Sadar,Bhelakoba,Assam,2011-2014
159,IV,Dhubri,39,Dhubri- Sadar,Aranya,Assam,2011-2014
160,IV,Dhubri,39,Dhubri- Sadar,Kismathasdaha-I,Assam,2011-2014
161,IV,Dhubri,40,Gauripur,Madhu Sailmari-I,Assam,2011-2014
162,IV,Dhubri,40,Gauripur,Madhu Sailmari-II,Assam,2011-2014
163,V,Hailakandi,41,Matizuri(Hailakandi),D/Sonapur-I,Assam,2011-2014
164,V,Hailakandi,41,Matizuri(Hailakandi),D/Sonapur-II,Assam,2011-2014
165,V,Hailakandi,41,Matizuri(Hailakandi),Matizuri,Assam,2011-2014
166,V,Karimganj,42,Karimganj,Ambari,Assam,2011-2014
167,V,Karimganj,42,Karimganj,Jatkapan,Assam,2011-2014
168,V,Cachar,43,Banskandi,Banskandi,Assam,2011-2014
169,V,Cachar,43,Banskandi,Machpara,Assam,2011-2014
170,V,Cachar,43,Banskandi,Karaikandi,Assam,2011-2014
171,VI,Karbi Anlong,44,Chillonijan,Japarajan,Assam,2011-2014
172,VI,Karbi Anlong,44,Chillonijan,Jabarajan,Assam,2011-2014
173,VI,Karbi Anlong,45,Bokajan,Balipathar,Assam,2011-2014
174,VI,Karbi Anlong,45,Bokajan,Balipathar No-1,Assam,2011-2014
175,VI,Karbi Anlong,45,Bokajan,Balipathar No-3,Assam,2011-2014
176,1,Samastipur,1,Samastipur,Raghunathpur,Bihar,2011-2014
177,1,Samastipur,2,Samastipur,Barbatta,Bihar,2011-2014
178,1,Samastipur,3,Rosra,Thahara Baijnathpur,Bihar,2011-2014
179,1,Madhubani,4,Jhanjharpur,Behat,Bihar,2011-2014
180,1,Madhubani,5,Jainagar,Dhaniapatti,Bihar,2011-2014
181,1,Darbhanga,6,Benaipur,Mahinam,Bihar,2011-2014
182,1,Muzaffarpur,7,Muzaffarpur(E),Chandrapatti,Bihar,2011-2014
183,1,Muzaffarpur,8,Muzaffarpur(W),Jagdishpur,Bihar,2011-2014
184,1,Muzaffarpur,9,Muzaffarpr(W),Mahmada,Bihar,2011-2014
185,1,Vaishali,10,Mahua,Bardiha,Bihar,2011-2014
186,1,East Champaran,11,Motihari Sadar,Pataura Lala Tola,Bihar,2011-2014
187,1,East Champaran,12,Chakia,Brindabandh,Bihar,2011-2014
188,1,West Champaran,13,Betia Sadar,Bishambharpur,Bihar,2011-2014
189,2,Saharsa,14,Saharsa Sadar,Kharagpur,Bihar,2011-2014
190,2,Saharsa,15,Simari Bakhtiarpur,Mahakhar,Bihar,2011-2014
191,2,Katihar,16,Kathiar,Jarlahi,Bihar,2011-2014
192,2,Madhepura,17,Madhepura,Sahugarh,Bihar,2011-2014
193,2,Supaul,18,Nirmali Sadar,Lahmania,Bihar,2011-2014
194,2,Purnea,19,Purnea Sadar,Dhansar,Bihar,2011-2014
195,3,Saran,20,Chapra Sadar,Ammadahi,Bihar,2011-2014
196,3,Siwan,21,Siwan Sadar,Bijayipur,Bihar,2011-2014
197,3,Gopalganj,22,Gopalganj Sadar,Mahamadpur,Bihar,2011-2014
198,3,Gopalganj,23,Gopalganj Sadar,Jhajhaba,Bihar,2011-2014
199,4,Patna,24,Masaudhi,Pothahi,Bihar,2011-2014
200,4,Patna,25,Paliganj,Mungla,Bihar,2011-2014
201,4,Nalanda,26,Biharsharif,Kitchani,Bihar,2011-2014
202,4,Nalanda,27,Hilsa,Mahamadpur,Bihar,2011-2014
203,4,Arrah,28,Arrah Sadar,Saraya,Bihar,2011-2014
204,4,Arrah,29,Piro,Pasour,Bihar,2011-2014
205,4,Arrah,30,Piro,Barap,Bihar,2011-2014
206,4,Baxur,31,Baxur,Padri,Bihar,2011-2014
207,4,Baxur,32,Baxur,Itadhi,Bihar,2011-2014
208,4,Baxur,33,Dumraon,Dulahpur,Bihar,2011-2014
209,4,Sasaram,34,Bikramganj,Matuli,Bihar,2011-2014
210,4,Kaimur,35,Mohania,Ghataon,Bihar,2011-2014
211,4,Gaya,36,Gaya Sadar,Belaganj,Bihar,2011-2014
212,4,Jahanabad,37,Jahanabad,Babhna,Bihar,2011-2014
213,4,Aurangabad,38,Aurangabad,Jagdishpur,Bihar,2011-2014
214,5,Begusarai,39,Teghra,Gonuchak,Bihar,2011-2014
215,5,Begusarai,40,Balia,Samastipur,Bihar,2011-2014
216,5,Munger,41,Tarapur,Devgaon,Bihar,2011-2014
217,5,Jamui,42,Jamui,Daulatpur,Bihar,2011-2014
218,5,Khagaria,43,Khagaria,Belasimiri,Bihar,2011-2014
219,5,Bhagalpur,44,Kahalgaon,Rampurkhahara.,Bihar,2011-2014
220,1,Deoghar,1,Deoghar,Janakpur,Jharkhand,2011-2014
221,1,Deoghar,2,Deoghar,Chakarana,Jharkhand,2011-2014
222,1,Dumka,3,Dumka,Pokhariya,Jharkhand,2011-2014
223,1,Jamtara,4,Jamtara,Udalbanni,Jharkhand,2011-2014
224,1,Hazaribag,5,Hazaribag,Mehashwara,Jharkhand,2011-2014
225,1,Hazaribag,6,Hazaribag,Pokhariya,Jharkhand,2011-2014
226,1,Hazaribag,7,Barhi,Bhushan dih,Jharkhand,2011-2014
227,1,Giridih,8,Giridih,Jarmule,Jharkhand,2011-2014
228,1,Bokaro,9,Bokaro,Baghadih,Jharkhand,2011-2014
229,1,Ranchi,10,Ranchi Sadar,Sukurhutu,Jharkhand,2011-2014
230,1,Ranchi,11,Khunti,Tua,Jharkhand,2011-2014
231,1,Ghat Shilla,12,Ghat Shilla,Pavara,Jharkhand,2011-2014
232,1,Dhanbad,13,Dhanbad Sadar,Baliyapur,Jharkhand,2011-2014
233,2,Palamu,14,Hasainabad,Budhua,Jharkhand,2011-2014
234,2,Palamu,15,Chhatarpur,Telari,Jharkhand,2011-2014
235,1,Tapi,1,Songarh,Mandal,Gujarat,2011-2014
236,1,Tapi,2,Valod,Delwada,Gujarat,2011-2014
237,2,Narmada,3,Nadod,Rundh,Gujarat,2011-2014
238,2,Bharuch,4,Valia,Pathar,Gujarat,2011-2014
239,3,Vadodara,5,Sankheda,Gola Gamdi,Gujarat,2011-2014
240,3,Panchmahals,6,Sahera,Vadi,Gujarat,2011-2014
241,3,Dahod,8,Zalod,Dungari,Gujarat,2011-2014
242,3,Vadodara,9,Savali,Juna Samlaya,Gujarat,2011-2014
243,3,Vadodara,10,Dabhoi,Thuvavi,Gujarat,2011-2014
244,3,Dahod,11,Fatepura,Bhojela,Gujarat,2011-2014
245,4,Kheda,12,Mahudha,Chunel,Gujarat,2011-2014
246,4,Gandhinagar,13,Mansa,Chadasana,Gujarat,2011-2014
247,4,Banaskantha,14,Deesa,Aaseda,Gujarat,2011-2014
248,4,Sabarkantha,15,Dhansura,Akarund,Gujarat,2011-2014
249,4,Anand,16,Tarapur,Khanpur,Gujarat,2011-2014
250,4,Kheda,17,Mahemdavad,Sinhuj,Gujarat,2011-2014
251,4,Mehsana,18,Unja,Amudh,Gujarat,2011-2014
252,4,Banaskantha,19,Dhanera,Valer,Gujarat,2011-2014
253,4,Mehsana,20,Mehsana,Bupapaldi,Gujarat,2011-2014
254,4,Ahmedabad,21,Sanand,Kunva,Gujarat,2011-2014
255,4,Sabarkantha,22,Himatnagar,Hadiyol,Gujarat,2011-2014
256,4,Anand,23,Khambhat,Undel,Gujarat,2011-2014
257,4,Sabarkantha,24,Talod,Harsol,Gujarat,2011-2014
258,5,Ahmedabad,25,Dholka,Dadusar,Gujarat,2011-2014
259,5,Bhavnagar,26,Bhavnagar,Budhel,Gujarat,2011-2014
260,5,Bhavnagar,27,Vallabhipur,Patna (Bhal),Gujarat,2011-2014
261,6,Junagarh,28,Sutarpada,Amrapur,Gujarat,2011-2014
262,6,Junagarh,29,Junagarh,Makhiyala,Gujarat,2011-2014
263,6,Bhavnagar,30,Mahuva,Bhadrod,Gujarat,2011-2014
264,6,Bhavnagar,32,Palitana,Mokhadka,Gujarat,2011-2014
265,6,Amreli,33,Savarkunla,Pithavadi,Gujarat,2011-2014
266,6,Amreli,34,Lathi,Rampar,Gujarat,2011-2014
267,6,Junagarh,35,Visavadar,Juni Chavand,Gujarat,2011-2014
268,6,Amreli,38,Lilya,Pujapadar,Gujarat,2011-2014
269,6,Junagarh,39,Una,Dhokadva,Gujarat,2011-2014
270,6,Rajkot,40,Jetpur,Jetalsar (Gam),Gujarat,2011-2014
271,7,Rajkot,41,Lodhika,Pal,Gujarat,2011-2014
272,7,Jamnagar,42,Jam Jodhapur,Gingani,Gujarat,2011-2014
273,7,Rajkot,43,Wankaner,Lunsar,Gujarat,2011-2014
274,7,Jamnagar,44,Lalpur,Moti Veraval,Gujarat,2011-2014
275,7,Jamnagar,45,Kalyanpur,Bankhodi,Gujarat,2011-2014
276,7,Jamnagar,47,Jamnagar,Moti Banugar,Gujarat,2011-2014
277,7,Surendhranagar,48,Muli,Jasapar,Gujarat,2011-2014
278,7,Surendhranagar,49,Chotila,Nava,Gujarat,2011-2014
279,7,Bhavnagar,50,Gadhada,Ugamedi,Gujarat,2011-2014
280,7,Jamnagar,51,Kalawad,Balanbhadi,Gujarat,2011-2014
281,7,Rajkot,52,Rajkot,Targhadiya,Gujarat,2011-2014
282,8,Patan,53,Chanasma,Dhamoda,Gujarat,2011-2014
283,8,Kachchha,54,Bhuj,Naranpur (p),Gujarat,2011-2014
284,8,Banaskantha,55,Deoder,Vakha,Gujarat,2011-2014
285,8,Banaskantha,57,Kankrej,Akoli (Maharaj Vas),Gujarat,2011-2014
286,8,Patan,58,Sami,Kuvarad,Gujarat,2011-2014
287,8,Surendhranagar,60,Halvad,Charadva,Gujarat,2011-2014
288,NaN,Chamba,1,Chamba,1.Nanu,Himachal Pradesh,2011-2014
289,NaN,Chamba,1,Chamba,2.Sarol,Himachal Pradesh,2011-2014
290,I,Churah,2,Chamba,1.Gwari,Himachal Pradesh,2011-2014
291,I,Churah,2,Chamba,2.Salahan,Himachal Pradesh,2011-2014
292,I,Churah,2,Chamba,3.Kuther,Himachal Pradesh,2011-2014
293,I,Kasauli,3,Solan,1.Chatera,Himachal Pradesh,2011-2014
294,I,Kasauli,3,Solan,2.Gulhari,Himachal Pradesh,2011-2014
295,I,Kasauli,3,Solan,3.Anji Chanala,Himachal Pradesh,2011-2014
296,I,Namhol,4,Bilaspur,1.Sai Naruan,Himachal Pradesh,2011-2014
297,I,Namhol,4,Bilaspur,2.Namhol,Himachal Pradesh,2011-2014
298,I,Namhol,4,Bilaspur,3.Gahota,Himachal Pradesh,2011-2014
299,I,Jhandutta,5,Bilaspur,1.Behran,Himachal Pradesh,2011-2014
300,I,Jhandutta,5,Bilaspur,2. Gallian,Himachal Pradesh,2011-2014
301,I,Jhandutta,5,Bilaspur,3.Behna Brahmna,Himachal Pradesh,2011-2014
302,I,Nalagarh,6,Solan,1.Chak,Himachal Pradesh,2011-2014
303,I,Nalagarh,6,Solan,2.Nanuwal,Himachal Pradesh,2011-2014
304,I,Nalagarh,6,Solan,3.Khera Nichla,Himachal Pradesh,2011-2014
305,I,Palampur,7,Kangra,1.Chowki,Himachal Pradesh,2011-2014
306,I,Palampur,7,Kangra,2.Khaled,Himachal Pradesh,2011-2014
307,I,Palampur,7,Kangra,3.Roudi,Himachal Pradesh,2011-2014
308,I,Barsar,8,Hamirpur,1.Saur,Himachal Pradesh,2011-2014
309,I,Barsar,8,Hamirpur,2.Mansuhi Jhikli,Himachal Pradesh,2011-2014
310,I,Barsar,8,Hamirpur,3.Mansuhi Majhli,Himachal Pradesh,2011-2014
311,I,Ramshahar,9,Solan,1.Chhachhi,Himachal Pradesh,2011-2014
312,I,Ramshahar,9,Solan,2.Kyar Da Ghrat,Himachal Pradesh,2011-2014
313,I,Ramshahar,9,Solan,3.Tungri,Himachal Pradesh,2011-2014
314,I,Arki,10,Solan,1.Galog,Himachal Pradesh,2011-2014
315,I,Arki,10,Solan,2.Jabal,Himachal Pradesh,2011-2014
316,I,Arki,10,Solan,3.Kothi Kunwal,Himachal Pradesh,2011-2014
317,I,Baldwara,11,Mandi,1.Baldwara,Himachal Pradesh,2011-2014
318,I,Baldwara,11,Mandi,2.Karni,Himachal Pradesh,2011-2014
319,I,Baldwara,11,Mandi,3.Padhian,Himachal Pradesh,2011-2014
320,I,Arki,12,Solan,1.Kothi,Himachal Pradesh,2011-2014
321,I,Arki,12,Solan,2.Kotli,Himachal Pradesh,2011-2014
322,I,Arki,12,Solan,3.Godhnu,Himachal Pradesh,2011-2014
323,I,Arki,12,Solan,3.Godhnu,Himachal Pradesh,2011-2014
324,I,Arki,12,Solan,3.Godhnu,Himachal Pradesh,2011-2014
325,I,Arki,12,Solan,3.Godhnu,Himachal Pradesh,2011-2014
326,II,Bhoranj,13,Hamirpur,1.Badehar,Himachal Pradesh,2011-2014
327,II,Bhoranj,13,Hamirpur,1.Badehar,Himachal Pradesh,2011-2014
328,II,Jhandutta,14,Bilaspur,1.Chat,Himachal Pradesh,2011-2014
329,II,Jhandutta,14,Bilaspur,2.Dharar Sani,Himachal Pradesh,2011-2014
330,II,Jhandutta,14,Bilaspur,3.Jawah,Himachal Pradesh,2011-2014
331,II,Jhandutta,14,Bilaspur,3.Jawah,Himachal Pradesh,2011-2014
332,II,Bilaspur,15,Bilaspur,1.Jamli,Himachal Pradesh,2011-2014
333,II,Bilaspur,15,Bilaspur,2.Neri,Himachal Pradesh,2011-2014
334,II,Bilaspur,15,Bilaspur,3.Lag,Himachal Pradesh,2011-2014
335,II,Bilaspur,15,Bilaspur,3.Lag,Himachal Pradesh,2011-2014
336,II,Sunder Nagar,16,Mandi,1.Jughan,Himachal Pradesh,2011-2014
337,II,Sunder Nagar,16,Mandi,2.Chhater,Himachal Pradesh,2011-2014
338,II,Sunder Nagar,16,Mandi,3.Sai,Himachal Pradesh,2011-2014
339,II,Sunder Nagar,16,Mandi,3.Sai,Himachal Pradesh,2011-2014
340,II,Amb,17,Una,1.Nakroh,Himachal Pradesh,2011-2014
341,II,Amb,17,Una,1.Nakroh,Himachal Pradesh,2011-2014

In [315]:
merged_df.to_csv('2011-2014.csv', index=False)